import type React from 'react'
import {
  HouseLine,
  ClipboardText,
  GearSix,
  CaretLeft,
  CaretRight,
  CaretDown,
  CaretRight as CaretRightIcon,
  Clock,
  WarningOctagon,
  CalendarBlank,
  Bookmarks,
  CheckCircle,
  ClockClockwise,
  Target,
  PencilSimple,
  Trash,
  CircleDashed,
  Spinner,
  MagnifyingGlass,
  HourglassHigh,
  ArrowLeft,
  Info,
  Flag,
  ListChecks,
  Note,
  ClockCounterClockwise,
  ArrowsOutSimple,
  ArrowsInSimple,
  Sliders,
  PaintBrush,
  ArrowsClockwise,
  Tag,
  Palette,
  Timer,
  X,
} from '@phosphor-icons/react'

import type { IconName } from '../../../types/themeIcon'

export type PhosphorIconComponent = React.ComponentType<any>

export const PHOSPHOR_MAP: Record<IconName, PhosphorIconComponent> = {
  home: HouseLine,
  clipboard: ClipboardText,
  gear: GearSix,
  'caret-left': CaretLeft,
  'caret-right': CaretRight,
  'caret-down': CaretDown,
  'caret-right-sm': CaretRightIcon,
  clock: Clock,
  warning: WarningOctagon,
  calendar: CalendarBlank,
  bookmarks: Bookmarks,
  'check-circle': CheckCircle,
  'clock-history': ClockClockwise,
  target: Target,
  edit: PencilSimple,
  trash: Trash,
  'circle-dashed': CircleDashed,
  spinner: Spinner,
  search: MagnifyingGlass,
  hourglass: HourglassHigh,
  'arrow-left': ArrowLeft,
  info: Info,
  flag: Flag,
  'list-checks': ListChecks,
  note: Note,
  history: ClockCounterClockwise,
  expand: ArrowsOutSimple,
  collapse: ArrowsInSimple,
  sliders: Sliders,
  'paint-brush': PaintBrush,
  refresh: ArrowsClockwise,
  tag: Tag,
  palette: Palette,
  timer: Timer,
  close: X,
}

