import type React from 'react'
import {
  RiArrowDownSLine,
  RiArrowLeftLine,
  RiArrowLeftSLine,
  RiArrowRightSLine,
  RiBookmarkLine,
  RiCalendarLine,
  RiCheckboxCircleLine,
  RiClipboardLine,
  RiCloseLine,
  RiDeleteBinLine,
  RiEdit2Line,
  RiEqualizerLine,
  RiErrorWarningLine,
  RiFlagLine,
  RiFullscreenExitLine,
  RiFullscreenLine,
  RiHistoryLine,
  RiHomeLine,
  RiHourglassLine,
  RiInformationLine,
  RiLoader2Line,
  RiPaintBrushLine,
  RiPaletteLine,
  RiPriceTag3Line,
  RiRefreshLine,
  RiSearchLine,
  RiSettings3Line,
  RiStickyNoteLine,
  RiTargetLine,
  RiTaskLine,
  RiTimeLine,
  RiTimerLine,
} from '@remixicon/react'

import type { IconName } from '../../../types/themeIcon'

export type RemixIconComponent = React.ComponentType<{
  size?: number | string
  className?: string
  style?: React.CSSProperties
}>

export const REMIX_MAP: Record<IconName, RemixIconComponent> = {
  home: RiHomeLine,
  clipboard: RiClipboardLine,
  gear: RiSettings3Line,
  'caret-left': RiArrowLeftSLine,
  'caret-right': RiArrowRightSLine,
  'caret-down': RiArrowDownSLine,
  'caret-right-sm': RiArrowRightSLine,
  clock: RiTimeLine,
  warning: RiErrorWarningLine,
  calendar: RiCalendarLine,
  bookmarks: RiBookmarkLine,
  'check-circle': RiCheckboxCircleLine,
  'clock-history': RiHistoryLine,
  target: RiTargetLine,
  edit: RiEdit2Line,
  trash: RiDeleteBinLine,
  'circle-dashed': RiLoader2Line,
  spinner: RiLoader2Line,
  search: RiSearchLine,
  hourglass: RiHourglassLine,
  'arrow-left': RiArrowLeftLine,
  info: RiInformationLine,
  flag: RiFlagLine,
  'list-checks': RiTaskLine,
  note: RiStickyNoteLine,
  history: RiHistoryLine,
  expand: RiFullscreenLine,
  collapse: RiFullscreenExitLine,
  sliders: RiEqualizerLine,
  'paint-brush': RiPaintBrushLine,
  refresh: RiRefreshLine,
  tag: RiPriceTag3Line,
  palette: RiPaletteLine,
  timer: RiTimerLine,
  close: RiCloseLine,
}
