import type React from 'react'
import {
  IconHome,
  IconClipboardText,
  IconSettings,
  IconChevronLeft,
  IconChevronRight,
  IconChevronDown,
  IconChevronRight as IconChevronRightAlt,
  IconClock,
  IconAlertOctagon,
  IconCalendar,
  IconBookmarks,
  IconCircleCheck,
  IconHistory,
  IconTarget,
  IconPencil,
  IconTrash,
  IconCircleDashed,
  IconLoader2,
  IconSearch,
  IconHourglass,
  IconArrowLeft,
  IconInfoCircle,
  IconFlag,
  IconListCheck,
  IconNote,
  IconClockHour3,
  IconArrowsMaximize,
  IconArrowsMinimize,
  IconAdjustments,
  IconBrush,
  IconRefresh,
  IconTag,
  IconPalette,
  IconAlarm,
  IconX,
} from '@tabler/icons-react'

import type { IconName } from '../../../types/themeIcon'

export type TablerIconComponent = React.ComponentType<any>

export const TABLER_MAP: Record<IconName, TablerIconComponent> = {
  home: IconHome,
  clipboard: IconClipboardText,
  gear: IconSettings,
  'caret-left': IconChevronLeft,
  'caret-right': IconChevronRight,
  'caret-down': IconChevronDown,
  'caret-right-sm': IconChevronRightAlt,
  clock: IconClock,
  warning: IconAlertOctagon,
  calendar: IconCalendar,
  bookmarks: IconBookmarks,
  'check-circle': IconCircleCheck,
  'clock-history': IconHistory,
  target: IconTarget,
  edit: IconPencil,
  trash: IconTrash,
  'circle-dashed': IconCircleDashed,
  spinner: IconLoader2,
  search: IconSearch,
  hourglass: IconHourglass,
  'arrow-left': IconArrowLeft,
  info: IconInfoCircle,
  flag: IconFlag,
  'list-checks': IconListCheck,
  note: IconNote,
  history: IconClockHour3,
  expand: IconArrowsMaximize,
  collapse: IconArrowsMinimize,
  sliders: IconAdjustments,
  'paint-brush': IconBrush,
  refresh: IconRefresh,
  tag: IconTag,
  palette: IconPalette,
  timer: IconAlarm,
  close: IconX,
}

